# Generated by Django 4.2.7 on 2026-01-30 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0017_alter_product_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de commande')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de facture')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('week', models.CharField(blank=True, max_length=2, null=True, verbose_name='Semaine')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Année')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Sous-total')),
                ('global_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise globale (%)')),
                ('total', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Total HT')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('received', 'Reçue'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de Commande Fournisseur',
                'verbose_name_plural': 'Bons de Commande Fournisseurs',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unit_price_ht', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire HT')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)')),
                ('total_ht', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Total HT')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité reçue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product', verbose_name='Produit')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
