# Generated by Django 4.2.7 on 2025-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('purchasing', 'Purchasing'), ('sales', 'Sales'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
