# Generated by Django 4.2.7 on 2026-02-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('purchasing', 'Purchasing'), ('sales', 'Sales'), ('customer', 'Customer'), ('responsable_achats', 'Responsable Achats')], default='customer', max_length=20),
        ),
    ]
