# Generated by Django 4.2.7 on 2025-09-24 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('transporteur', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('prepare', 'En préparation'), ('en_route', 'En route'), ('livre', 'Livré')], max_length=50)),
                ('date_expedition', models.DateField(blank=True, null=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('colis', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
            ],
        ),
    ]
