# Generated by Django 4.2.7 on 2025-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='colis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='statut',
            field=models.CharField(choices=[('prepare', 'En préparation'), ('en_route', 'En route'), ('livre', 'Livré')], default='prepare', max_length=50),
        ),
    ]
