# Generated by Django 4.2.7 on 2025-10-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_pdf',
        ),
    ]
