# Generated by Django 4.2.7 on 2025-12-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_invoice_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='fournisseur',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
