# Generated by Django 4.2.7 on 2025-12-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_purchaseorder_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warranty_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='warranty_vehicle_mileage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warranty_vehicle_registration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
