# Generated by Django 4.2.7 on 2026-03-08 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_order_delivery_cost_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cri_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid now via CRI', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cri_remaining',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining unpaid amount (loan)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cri_remarque',
            field=models.TextField(blank=True, help_text='CRI payment note', null=True),
        ),
        migrations.CreateModel(
            name='CRIBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Total unpaid CRI amount carried over from previous orders', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cri_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
