# Generated by Django 4.2.7 on 2025-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
