# Generated by Django 4.2.7 on 2025-09-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_stockmovement_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(default='PneuShop Tunisia', max_length=255)),
                ('description', models.TextField(default='Votre spécialiste en pneumatiques')),
                ('adresse', models.TextField(default='Avenue Habib Bourguiba, Tunis')),
                ('telephone', models.CharField(default='+216 71 123 456', max_length=20)),
                ('email', models.EmailField(default='contact@pneushop.tn', max_length=254)),
                ('horaires', models.CharField(default='Lun-Sam: 8h-18h', max_length=255)),
                ('email_commandes', models.BooleanField(default=True)),
                ('email_stock', models.BooleanField(default=True)),
                ('sms_clients', models.BooleanField(default=False)),
                ('push_admin', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=30)),
                ('mot_de_passe_force', models.BooleanField(default=True)),
                ('authentification_double', models.BooleanField(default=False)),
                ('journalisation', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('sauvegarde_auto', models.BooleanField(default=True)),
                ('langue_principale', models.CharField(default='fr', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
