# Generated by Django 4.2.7 on 2025-12-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Désignation'),
        ),
        migrations.AddField(
            model_name='product',
            name='emplacement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emplacement'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabrication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fabrication'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
    ]
