# Generated by Django 4.2.7 on 2025-12-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_designation_product_emplacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Image principale'),
        ),
    ]
