# Generated by Django 4.2.7 on 2025-12-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_image_2_product_image_3_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Taille'),
        ),
    ]
