# Generated by Django 4.2.7 on 2026-02-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_max',
            field=models.PositiveIntegerField(default=100, verbose_name='Stock maximum'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock minimum (alerte)'),
        ),
    ]
